import { UserionDetections } from "../userion-detections";

export const UserionDeviceDetection = {
  type: UserionDetections.DEVICE,
  checks: [
    /\b(sch-i[89]0\d|shw-m380s|sm-[pt]\w{2,4}|gt-[pn]\d{2,4}|sgh-t8[56]9|nexus 10)/i,
    /\b((?:s[cgp]h|gt|sm)-\w+|galaxy nexus)/i,
    /samsung[- ]([-\w]+)/i,
    /sec-(sgh\w+)/i,
    /\((ip(?:hone|od)[\w ]*);/i,
    /\((ipad);[-\w\),; ]+apple/i,
    /applecoremedia\/[\w\.]+ \((ipad)/i,
    /\b(ipad)\d\d?,\d\d?[;\]].+ios/i,
    /\b((?:ag[rs][23]?|bah2?|sht?|btv)-a?[lw]\d{2})\b(?!.+d\/s)/i,
    /(?:huawei|honor)([-\w ]+)[;\)]/i,
    /\b(nexus 6p|\w{2,4}-[atu]?[ln][01259x][012359][an]?)\b(?!.+d\/s)/i,
    /\b(poco[\w ]+)(?: bui|\))/i,
    /\b; (\w+) build\/hm\1/i,
    /\b(hm[-_ ]?note?[_ ]?(?:\d\w)?) bui/i,
    /\b(redmi[\-_ ]?(?:note|k)?[\w_ ]+)(?: bui|\))/i,
    /\b(mi[-_ ]?(?:a\d|one|one[_ ]plus|note lte|max)?[_ ]?(?:\d?\w?)[_ ]?(?:plus|se|lite)?)(?: bui|\))/i,
    /\b(mi[-_ ]?(?:pad)(?:[\w_ ]+))(?: bui|\))/i,
    /; (\w+) bui.+ oppo/i,
    /\b(cph[12]\d{3}|p(?:af|c[al]|d\w|e[ar])[mt]\d0|x9007|a101op)\b/i,
    /vivo (\w+)(?: bui|\))/i,
    /\b(v[12]\d{3}\w?[at])(?: bui|;)/i,
    /\b(rmx[12]\d{3})(?: bui|;|\))/i,
    /\b(milestone|droid(?:[2-4x]| (?:bionic|x2|pro|razr))?:?( 4g)?)\b[\w ]+build\//i,
    /\bmot(?:orola)?[- ](\w*)/i,
    /((?:moto[\w\(\) ]+|xt\d{3,4}|nexus 6)(?= bui|\)))/i,
    /\b(mz60\d|xoom[2 ]{0,2}) build\//i,
    /((?=lg)?[vl]k\-?\d{3}) bui| 3\.[-\w; ]{10}lg?-([06cv9]{3,4})/i,
    /(lm(?:-?f100[nv]?|-[\w\.]+)(?= bui|\))|nexus [45])/i,
    /\blg[-e;\/ ]+((?!browser|netcast|android tv)\w+)/i,
    /\blg-?([\d\w]+) bui/i,
    /(ideatab[-\w ]+)/i,
    /lenovo ?(s[56]000[-\w]+|tab(?:[\w ]+)|yt[-\d\w]{6}|tb[-\d\w]{6})/i,
    /(?:maemo|nokia).*(n900|lumia \d+)/i,
    /nokia[-_ ]?([-\w\.]*)/i,
    /(pixel c)\b/i,
    /droid.+; (pixel[\daxl ]{0,6})(?: bui|\))/i,
    /droid.+ (a?\d[0-2]{2}so|[c-g]\d{4}|so[-gl]\w+|xq-a\w[4-7][12])(?= bui|\).+chrome\/(?![1-6]{0,1}\d\.))/i,
    /sony tablet [ps]/i,
    /\b(?:sony)?sgp\w+(?: bui|\))/i,
    / (kb2005|in20[12]5|be20[12][59])\b/i,
    /(?:one)?(?:plus)? (a\d0\d\d)(?: b|\))/i,
    /(alexa)webm/i,
    /(kf[a-z]{2}wi)( bui|\))/i,
    /(kf[a-z]+)( bui|\)).+silk\//i,
    /((?:sd|kf)[0349hijorstuw]+)( bui|\)).+silk\//i,
    /(playbook);[-\w\),; ]+(rim)/i,
    /\b((?:bb[a-f]|st[hv])100-\d)/i,
    /\(bb10; (\w+)/i,
    /(?:\b|asus_)(transfo[prime ]{4,10} \w+|eeepc|slider \w+|nexus 7|padfone|p00[cj])/i,
    / (z[bes]6[027][012][km][ls]|zenfone \d\w?)\b/i,
    /(nexus 9)/i,
    /(htc)[-;_ ]{1,2}([\w ]+(?=\)| bui)|\w+)/i,
    /(zte)[- ]([\w ]+?)(?: bui|\/|\))/i,
    /(alcatel|geeksphone|nexian|panasonic|sony(?!-bra))[-_ ]?([-\w]*)/i,
    /droid.+; ([ab][1-7]-?[0178a]\d\d?)/i,
    /droid.+; (m[1-5] note) bui/i,
    /\bmz-([-\w]{2,})/i,
    /\b(sh-?[altvz]?\d\d[a-ekm]?)/i,
    /(blackberry|benq|palm(?=\-)|sonyericsson|acer|asus|dell|meizu|motorola|polytron)[-_ ]?([-\w]*)/i,
    /(hp) ([\w ]+\w)/i,
    /(asus)-?(\w+)/i,
    /(microsoft); (lumia[\w ]+)/i,
    /(lenovo)[-_ ]?([-\w]+)/i,
    /(jolla)/i,
    /(oppo) ?([\w ]+) bui/i,
    /(archos) (gamepad2?)/i,
    /(hp).+(touchpad(?!.+tablet)|tablet)/i,
    /(kindle)\/([\w\.]+)/i,
    /(nook)[\w ]+build\/(\w+)/i,
    /(dell) (strea[kpr\d ]*[\dko])/i,
    /(le[- ]+pan)[- ]+(\w{1,9}) bui/i,
    /(trinity)[- ]*(t\d{3}) bui/i,
    /(gigaset)[- ]+(q\w{1,9}) bui/i,
    /(vodafone) ([\w ]+)(?:\)| bui)/i,
    /(surface duo)/i,
    /droid [\d\.]+; (fp\du?)(?: b|\))/i,
    /(u304aa)/i,
    /\bsie-(\w*)/i,
    /\b(rct\w+) b/i,
    /\b(venue[\d ]{2,7}) b/i,
    /\b(q(?:mv|ta)\w+) b/i,
    /\b(?:barnes[& ]+noble |bn[rt])([\w\+ ]*) b/i,
    /\b(tm\d{3}\w+) b/i,
    /\b(k88) b/i,
    /\b(nx\d{3}j) b/i,
    /\b(gen\d{3}) b.+49h/i,
    /\b(zur\d{3}) b/i,
    /\b((zeki)?tb.*\b) b/i,
    /\b([yr]\d{2}) b/i,
    /\b(dragon[- ]+touch |dt)(\w{5}) b/i,
    /\b(ns-?\w{0,9}) b/i,
    /\b((nxa|next)-?\w{0,9}) b/i,
    /\b(xtreme\_)?(v(1[045]|2[015]|[3469]0|7[05])) b/i,
    /\b(lvtel\-)?(v1[12]) b/i,
    /\b(ph-1) /i,
    /\b(v(100md|700na|7011|917g).*\b) b/i,
    /\b(trio[-\w\. ]+) b/i,
    /\btu_(1491) b/i,
    /(shield[\w ]+) b/i,
    /(sprint) (\w+)/i,
    /(kin\.[onetw]{3})/i,
    /droid.+; (cc6666?|et5[16]|mc[239][23]x?|vc8[03]x?)\)/i,
    /droid.+; (ec30|ps20|tc[2-8]\d[kx])\)/i,
    /droid .+?; ([^;]+?)(?: bui|\) applew).+? mobile safari/i,
    /droid .+?; ([^;]+?)(?: bui|\) applew).+?(?! mobile) safari/i,
    /\b((tablet|tab)[;\/]|focus\/\d(?!.+mobile))/i,
    /(phone|mobile(?:[;\/]| safari)|pda(?=.+windows ce))/i,
    /(android[-\w\. ]{0,9});.+buil/i,
  ],
};
