import { KeyCodesEnum } from "@lib/enums";
import { KeyCodesUnion } from "@lib/types";

export const KeyCodes: Map<KeyCodesUnion, KeyCodesEnum> = new Map([
  ["Space", KeyCodesEnum.Space],
  [";", KeyCodesEnum.Semicolon],
  ["=", KeyCodesEnum.Equal],
  [",", KeyCodesEnum.Comma],
  ["-", KeyCodesEnum.Minus],
  [".", KeyCodesEnum.Period],
  ["/", KeyCodesEnum.Slash],
  ["`", KeyCodesEnum.Backquote],
  ["[", KeyCodesEnum.BracketLeft],
  ["\\", KeyCodesEnum.Backslash],
  ["]", KeyCodesEnum.BracketRight],
  ["'", KeyCodesEnum.Quote],
  ["1", KeyCodesEnum.Digit1],
  ["2", KeyCodesEnum.Digit2],
  ["3", KeyCodesEnum.Digit3],
  ["4", KeyCodesEnum.Digit4],
  ["5", KeyCodesEnum.Digit5],
  ["6", KeyCodesEnum.Digit6],
  ["7", KeyCodesEnum.Digit7],
  ["8", KeyCodesEnum.Digit8],
  ["9", KeyCodesEnum.Digit9],
  ["0", KeyCodesEnum.Digit0],
  ["a", KeyCodesEnum.KeyA],
  ["b", KeyCodesEnum.KeyB],
  ["c", KeyCodesEnum.KeyC],
  ["d", KeyCodesEnum.KeyD],
  ["e", KeyCodesEnum.KeyE],
  ["f", KeyCodesEnum.KeyF],
  ["g", KeyCodesEnum.KeyG],
  ["h", KeyCodesEnum.KeyH],
  ["i", KeyCodesEnum.KeyI],
  ["j", KeyCodesEnum.KeyJ],
  ["k", KeyCodesEnum.KeyK],
  ["l", KeyCodesEnum.KeyL],
  ["m", KeyCodesEnum.KeyM],
  ["n", KeyCodesEnum.KeyN],
  ["o", KeyCodesEnum.KeyO],
  ["p", KeyCodesEnum.KeyP],
  ["q", KeyCodesEnum.KeyQ],
  ["r", KeyCodesEnum.KeyR],
  ["s", KeyCodesEnum.KeyS],
  ["t", KeyCodesEnum.KeyT],
  ["u", KeyCodesEnum.KeyU],
  ["v", KeyCodesEnum.KeyV],
  ["w", KeyCodesEnum.KeyW],
  ["x", KeyCodesEnum.KeyX],
  ["y", KeyCodesEnum.KeyY],
  ["z", KeyCodesEnum.KeyZ],
]);
